create table if not exists "public"."beans" (
  id bigint generated by default as identity primary key,
  user_id uuid,
  name text not null,
  origin text not null,
  variety text,
  process text not null,
  created_at timestamp default now(),
  updated_at timestamp default now(),

  constraint "auth.users" foreign key (user_id) references auth.users(id) on delete cascade
);

-- RLS有効化
alter table public.beans enable row level security;

-- 自分だけ見れるポリシー
create policy "Users can see their beans"
on public.beans
for select
using (user_id = auth.uid());