create table if not exists "public"."roasts" (
  id bigint generated by default as identity primary key,
  user_id uuid,
  bean_id bigint,
  total_time text,
  profile json,
  note text,
  level text,
  created_at timestamp default now(),
  updated_at timestamp default now(),

  constraint "auth.users" foreign key (user_id) references auth.users(id) on delete cascade,
  constraint beans foreign key (bean_id) references beans(id) on delete cascade
);

-- RLS有効化
alter table public.roasts enable row level security;

-- 自分だけ見れるポリシー
create policy "Users can see their roasts"
on public.roasts
for select
using (user_id = auth.uid());